<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <title>{{ $report['title'] }}</title>
    <style>
        @page { margin: 28px 28px 42px 28px; }
        body { font-family: DejaVu Sans, sans-serif; color: #1f2937; font-size: 10.5px; line-height: 1.45; }
        .header { display: table; width: 100%; margin-bottom: 18px; }
        .brand-mark { display: table-cell; width: 52px; vertical-align: top; }
        .brand-box { width: 42px; height: 42px; border-radius: 10px; background: #4F8EF7; color: #fff; text-align: center; line-height: 42px; font-size: 18px; font-weight: bold; }
        .brand { display: table-cell; vertical-align: top; }
        .meta { display: table-cell; text-align: right; vertical-align: top; font-size: 9.5px; color: #64748b; }
        h1 { margin: 0; font-size: 20px; color: #111827; }
        .subtitle { margin-top: 3px; color: #64748b; font-size: 11px; }
        .divider { border-top: 2px solid #E5E7EB; margin: 14px 0 16px; }
        .filters { margin-bottom: 14px; padding: 10px 12px; background: #F8FAFC; border: 1px solid #E5E7EB; border-radius: 10px; }
        .filters strong { color: #334155; }
        table { width: 100%; border-collapse: collapse; page-break-inside: auto; }
        thead { display: table-header-group; }
        tfoot { display: table-row-group; }
        tr { page-break-inside: avoid; page-break-after: auto; }
        th { background: #EEF2F7; color: #334155; text-transform: uppercase; font-size: 8.5px; letter-spacing: .04em; padding: 7px 6px; border: 1px solid #D8DEE8; text-align: left; }
        td { padding: 7px 6px; border: 1px solid #E5E7EB; vertical-align: top; }
        tbody tr:nth-child(even) td { background: #F9FAFB; }
        .num { text-align: right; }
        .center { text-align: center; }
        .summary { margin-top: 18px; padding: 12px; background: #EFF6FF; border: 1px solid #BFDBFE; border-radius: 12px; }
        .summary-title { margin-bottom: 8px; font-weight: bold; color: #1E3A8A; }
        .summary-grid { width: 100%; }
        .summary-grid td { border: 0; padding: 3px 6px; background: transparent !important; }
        .summary-grid td:first-child { font-weight: bold; color: #334155; width: 45%; }
        .footer { position: fixed; left: 0; right: 0; bottom: -26px; height: 24px; color: #94A3B8; font-size: 9px; border-top: 1px solid #E5E7EB; padding-top: 8px; }
        .footer .right { float: right; }
        .pagenum:before { content: counter(page); }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand-mark"><div class="brand-box">AO</div></div>
        <div class="brand">
            <h1>{{ $report['title'] }}</h1>
            <div class="subtitle">{{ $report['app_name'] }} - Periode {{ $report['period_label'] }}</div>
        </div>
        <div class="meta">
            <div>Generated: {{ $report['generated_at']->format('d/m/Y H:i') }}</div>
            <div>Generated by: {{ $report['generated_by'] }}</div>
        </div>
    </div>

    <div class="divider"></div>

    <div class="filters">
        <strong>Applied filters:</strong>
        @foreach($report['filters'] as $label => $value)
            {{ $label }}: {{ $value }}@if(!$loop->last) | @endif
        @endforeach
    </div>

    <table>
        <thead>
            <tr>
                @foreach($report['headings'] as $heading)
                    <th>{{ $heading }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @forelse($report['rows'] as $row)
                <tr>
                    @foreach($row as $key => $value)
                        @php $isNumeric = is_numeric($value) && !in_array($key, ['No']); @endphp
                        <td class="{{ $key === 'No' ? 'center' : ($isNumeric ? 'num' : '') }}">
                            @if(str_contains(strtolower($key), 'fee'))
                                Rp {{ number_format((float) $value, 0, ',', '.') }}
                            @else
                                {{ $value }}
                            @endif
                        </td>
                    @endforeach
                </tr>
            @empty
                <tr><td colspan="{{ count($report['headings']) }}" class="center">Tidak ada data.</td></tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <div class="summary-title">Summary</div>
        <table class="summary-grid">
            @foreach($report['summary'] as $label => $value)
                <tr>
                    <td>{{ $label }}</td>
                    <td>
                        @if(str_contains(strtolower($label), 'fee') || str_contains(strtolower($label), 'value') || str_contains(strtolower($label), 'amount'))
                            Rp {{ number_format((float) $value, 0, ',', '.') }}
                        @else
                            {{ $value }}
                        @endif
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

    <div class="footer">
        Printed by {{ $report['app_name'] }} - {{ now()->format('d/m/Y H:i') }}
        <span class="right">Page <span class="pagenum"></span></span>
    </div>
</body>
</html>
