<?php

namespace App\Exports\Reports;

use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithCustomStartCell;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

abstract class BaseReportExport implements FromCollection, WithHeadings, WithStyles, WithEvents, ShouldAutoSize, WithCustomStartCell, WithTitle
{
    public function __construct(protected array $report)
    {
    }

    public function collection(): Collection
    {
        return $this->report['rows']->map(fn (array $row) => array_values($row));
    }

    public function headings(): array
    {
        return $this->report['headings'];
    }

    public function startCell(): string
    {
        return 'A9';
    }

    public function title(): string
    {
        return str($this->report['type'])->headline()->limit(28, '')->toString();
    }

    public function styles(Worksheet $sheet): array
    {
        return [
            1 => ['font' => ['bold' => true, 'size' => 18, 'color' => ['rgb' => '1E293B']]],
            2 => ['font' => ['bold' => true, 'size' => 12, 'color' => ['rgb' => '64748B']]],
            9 => [
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '4F8EF7']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ],
        ];
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event) {
                $sheet = $event->sheet->getDelegate();
                $lastColumn = $sheet->getHighestColumn();
                $headingRow = 9;
                $firstDataRow = 10;
                $lastDataRow = max($firstDataRow, $firstDataRow + $this->report['rows']->count() - 1);
                $summaryStart = $lastDataRow + 3;

                $sheet->mergeCells("A1:{$lastColumn}1");
                $sheet->mergeCells("A2:{$lastColumn}2");
                $sheet->setCellValue('A1', $this->report['title']);
                $sheet->setCellValue('A2', $this->report['app_name'] . ' - Periode: ' . $this->report['period_label']);
                $sheet->setCellValue('A4', 'Generated at');
                $sheet->setCellValue('B4', $this->report['generated_at']->format('d/m/Y H:i'));
                $sheet->setCellValue('A5', 'Generated by');
                $sheet->setCellValue('B5', $this->report['generated_by']);
                $sheet->setCellValue('A6', 'Applied filters');
                $sheet->setCellValue('B6', collect($this->report['filters'])->map(fn ($value, $key) => $key . ': ' . $value)->implode(' | '));

                $sheet->getStyle("A1:{$lastColumn}2")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
                $sheet->getStyle('A4:A6')->getFont()->setBold(true);
                $sheet->getStyle("A{$headingRow}:{$lastColumn}{$lastDataRow}")->applyFromArray([
                    'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'D9E2EC']]],
                    'alignment' => ['vertical' => Alignment::VERTICAL_CENTER],
                ]);
                $sheet->getStyle("A{$headingRow}:{$lastColumn}{$headingRow}")->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
                $sheet->getRowDimension($headingRow)->setRowHeight(24);
                $sheet->freezePane('A10');
                $sheet->setAutoFilter("A{$headingRow}:{$lastColumn}{$headingRow}");

                for ($row = $firstDataRow; $row <= $lastDataRow; $row++) {
                    if (($row - $firstDataRow) % 2 === 1) {
                        $sheet->getStyle("A{$row}:{$lastColumn}{$row}")->getFill()
                            ->setFillType(Fill::FILL_SOLID)
                            ->getStartColor()->setRGB('F8FAFC');
                    }
                }

                $currencyColumns = $this->currencyColumns();
                foreach ($currencyColumns as $column) {
                    $sheet->getStyle("{$column}{$firstDataRow}:{$column}{$lastDataRow}")
                        ->getNumberFormat()->setFormatCode('"Rp" #,##0');
                    $sheet->getStyle("{$column}{$firstDataRow}:{$column}{$lastDataRow}")
                        ->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
                }

                foreach ($this->numericColumns() as $column) {
                    $sheet->getStyle("{$column}{$firstDataRow}:{$column}{$lastDataRow}")
                        ->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
                }

                $sheet->setCellValue("A{$summaryStart}", 'Summary');
                $sheet->getStyle("A{$summaryStart}")->getFont()->setBold(true)->setSize(13);
                $summaryRow = $summaryStart + 1;
                foreach ($this->report['summary'] as $label => $value) {
                    $sheet->setCellValue("A{$summaryRow}", $label);
                    $sheet->setCellValue("B{$summaryRow}", $value);
                    $summaryRow++;
                }
                $sheet->getStyle("A{$summaryStart}:B" . ($summaryRow - 1))->applyFromArray([
                    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => 'EEF6FF']],
                    'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'BFDBFE']]],
                ]);
                $sheet->getStyle("A" . ($summaryStart + 1) . ":A" . ($summaryRow - 1))->getFont()->setBold(true);
            },
        ];
    }

    protected function numericColumns(): array
    {
        return [];
    }

    protected function currencyColumns(): array
    {
        return [];
    }
}
